config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :costumes, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:create, :edit, :update]
  end
  resources :bookings, only: [:destroy] do
     patch :accept, :reject
   end
  resources :dashboard, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :costume
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/costume.rb
class Costume < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo, dependent: :destroy
  validates :name, :size, :price_per_day, :category, presence: true
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

 
  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :costumes, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    find_costume
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.costume = @costume
    authorize @booking
    if @booking.save
      flash.notice = "Booking created!"
      redirect_to dashboard_index_path
    else
      render "costumes/show"
    end
  end

  def edit
    find_costume
    find_booking
    authorize @booking
  end

  def update
    find_booking
    authorize @booking
    if @booking.update(booking_params)
      redirect_to dashboard_index_path
    else
      render :edit
    end
  end

  def destroy
    find_booking
    authorize @booking
    @booking.destroy
    flash.notice = "Booking deleted!"
    redirect_to dashboard_index_path
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    authorize @booking
    @booking.status = "confirmed"
    @booking.save
    flash.notice = "Booking accepted!"
    redirect_to dashboard_index_path
  end

  def reject
    @booking = Booking.find(params[:booking_id])
    authorize @booking
    @booking.status = "rejected"
    @booking.save
    flash.notice = "Booking rejected!"
    redirect_to dashboard_index_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end

  def find_costume
    @costume = Costume.find(params[:costume_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @costumes = policy_scope(Costume)
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query or category ILIKE :query"
      @costumes = Costume.where(sql_query, query: "%#{params[:query]}%")
    else
      @costumes = Costume.all
    end

    @markers = @costumes.geocoded.map do |costume|
      {
        lat: costume.latitude,
        lng: costume.longitude
      }
    end
  end

  def show
    find_costume
    @booking = Booking.new
    authorize @costume
    @user = current_user
  end

  def new
    @costume = Costume.new
    authorize @costume
  end

  def create
    @costume = Costume.new(costume_params)
    authorize @costume
    @costume.user = current_user
    if @costume.save
      current_user.lender = true
      current_user.save
      flash.notice = "Costume created!"
      redirect_to costume_path(@costume)
    else
      render :new
    end
  end

  def destroy
    find_costume
    authorize @costume
    @costume.destroy
    flash.notice = "Costume deleted!"
    redirect_to dashboard_index_path
  end

  private

  def costume_params
    params.require(:costume).permit(:name, :size, :price_per_day, :category, :description, :photo, :address)
  end

  def find_costume
    @costume = Costume.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = policy_scope(User)
    @my_costumes_ids = @user.costumes.map do |costume|
      costume.id
    end
    @received_bookings = Booking.where(costume_id: @my_costumes_ids)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<%= render "shared/navbar" %>
<h3>Change Booking Status</h3>
<%= simple_form_for [@costume, @booking] do |f| %>
  <%= f.input :status, :collection => %w[Confirmed Rejected] %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/costumes/index.html.erb
<%= render "shared/navbar" %>
<!-- <h1 style="margin-left: 16px;">All costumes</h1> -->

<div class="content" id="cardsmap">

  <div id="cardsleft">
    <% @costumes.each do |costume| %>
      <% if costume.photo.attached? %>
          <div class="my-card-background" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= cl_image_path costume.photo.key %>)">
            <%= link_to costume.name, costume_path(costume), class: "my-card" %>
          </div>
      <% else %>
          <div class="my-card-background" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4))">
            <%= link_to costume.name, costume_path(costume), class: "my-card" %>
          </div>
      <% end %>
    <% end %>
  </div>

  <div id="map"
     style="width: 400px; height: calc(100vh - 64px); box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.2); position: sticky; top: 64px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/costumes/new.html.erb
<%= render "shared/navbar" %>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="costume-form p-4 mt-4 mb-4">
        <h2>Add a new costume</h2>

        <%= simple_form_for [@costume] do |f| %>
          <%= f.input :name %>
          <%= f.input :size %>
          <%= f.input :price_per_day%>
          <%= f.input :category %>
          <%= f.input :description %>
          <%= f.input :address %>
          <label class="btn btn-success">
            + Upload picture (optional)
            <span style="display:none;">
              <%= f.input :photo, as: :file %>
            </span>
          </label>
          <br>
          <%= f.button :submit, "+ Add costume", class: "btn btn-success" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/costumes/show.html.erb
<%= render "shared/navbar" %>
<br>
<div class="container">
  <div class="row justify-content-between">

    <div class="col-12 col-md-6">
      <% if @costume.photo.attached? %>
        <div class="show-image mb-3" style="background-image: url(<%= cl_image_path @costume.photo.key %>)"></div>
      <% else %>
        <div class="show-image mb-3 d-flex justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)); color: rgba(0,0,0,0.5)">
          <p><em>No image uploaded.</em></p>
        </div>
      <% end %>
    </div>

    <div class="col-12 col-md-6">
      <div class="show-info p-4">
        <h2><%= @costume.name %> </h2>
        <hr>

       <ul>
        <li>Costume name: <%= @costume.name %></li>
        <li>Size: <%= @costume.size %></li>
        <li>Price per day: <%= @costume.price_per_day %> €</li>
        <li>Category: <%= @costume.category %></li>
        <li>Description: <%= @costume.description %></li>
        <li>Address: <%= @costume.address %></li>
       </ul>

        <br>
        <h2>Book this costume</h2>
        <hr>

        <% if @costume.user != @user %>
          <div id='booking-dates' data-unavailable="<%= @costume.unavailable_dates.to_json %>">
            <%= simple_form_for [@costume, @booking] do |f| %>
            <%= f.input :start_date, as: :string %>
            <%= f.input :end_date, as: :string %>
            <%= f.button :submit, "+ Confirm booking", class: "btn btn-success" %>
          </div>
          <% end %>
        <% else %>
       
          <div class="show-owner">
            <em>This costume is offered by you - you cannot book it.</em>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/dashboard/index.html.erb
<%= render "shared/navbar" %>
<br>
<div class="container" >
  <h1>Dashboard</h1>

  <br>

  <div>
    <h3>My Bookings</h3>
    <hr>

    <% if @user.bookings.empty? %>
      <p> You don't have any bookings. :(  <%= link_to "Have a look at our costumes!", costumes_path %> </p>
    <% end %>

    <ul class="pl-0">
      <% @user.bookings.each do |booking| %>
        <div class="card ml-0">
          <li>
            <div class="grid-item">
              <strong>Name:</strong>  <%= link_to booking.costume.name, costume_path(booking.costume)%> |
              <strong>Start date:</strong>  <%= booking.start_date %> |
              <strong>End date:</strong>  <%= booking.end_date %> |
              <strong>Status:</strong>  <%= booking.status %>
            </div>
            <div class="item"></div>
            <div class="grid-item">
              <button type="button" class="btn btn-danger"> <%= link_to "✘ Cancel", booking_path(booking), method: :delete, data: { confirm: "Are you sure?"} %></button>
            </div>
          </li>
        </div>
      <% end %>
    </ul>
  </div>

  <% if @user.lender %>
    <div>
      <br>
      <br>
      <h3>Received Bookings</h3>
      <hr>

      <% if @received_bookings.empty? %>
        <p> You have not received any bookings. :( </p>
      <% end %>

      <ul class="pl-0">
        <% @received_bookings.each do |booking| %>
          <div class="card ml-0">
            <li>
              <div class="grid-item">
                <strong>Name:</strong> <%= link_to booking.costume.name, costume_path(booking.costume)%> |
                <strong> Start date:</strong> <%= booking.start_date %> |
                <strong> End date:</strong> <%= booking.end_date %> |
                <strong> Status:</strong> <%= booking.status %>
              </div>
              <div class="item"></div>
              <% if booking.status == "pending"%>
                <div class="grid-item">
                  <button type="button" class="btn btn-success"> <%= link_to "✔ Accept", booking_accept_path(booking), method: :patch,  data: { confirm: "Are you sure you want to accept this booking?" }%></button>
                  <button type="button" class="btn btn-danger"> <%= link_to "✘ Reject", booking_reject_path(booking), method: :patch,  data: { confirm: "Are you sure you want to reject this booking?" } %></button>
                </div>
              <% end %>
            </li>
         </div>
       <% end %>
      </ul>
    </div>

    <div>
      <br>
      <br>
      <h3>My Costumes</h3>
      <hr>

      <ul class="pl-0">
        <% @user.costumes.each do |costume| %>
          <div class="card ml-0">
            <li>
              <div class="grid-item">
                <!-- implement small image + placeholder -->
                <strong>Name:</strong> <%= costume.name %> |
                <strong>Size:</strong> <%= costume.size %> |
                <strong>Price per day:</strong> <%= costume.price_per_day %> € |
                <strong>Category:</strong> <%= costume.category %>
                <br>
                <strong>Description:</strong> <%= costume.description %>
             </div>
             <div class="item"></div>
             <div class="grid-item">
               <button type="button" class="btn btn-light" > <%= link_to "→ Show", costume_path(costume) %></button>
               <button type="button" class="btn btn-danger"><%= link_to "✘ Delete", costume_path(costume), method: :delete, data: { confirm: "Are you sure?" } %></button>
             </div>
            </li>
          </div>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Costume Carousel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div id="flash-messages">
      <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(<%= cl_image_path 'v1605714307/Vader_oxokbz.jpg' %>)">
  <div class="container">
    <div class="logo mb-5" class="mb-5">
      <%= cl_image_tag('v1605714662/logo_nau1de.png') %>
      <!-- <img class="logo_image " src= "<%= asset_path('logo.png') %>"> -->
      <div class="logo__text">May the force be with you!</div>
    </div>
      <div id="Text" class="mb-5" >
        <h1>Be the star of the next party!</h1>
        <p>Find the perfect costume</p>
      </div>
      <div>
        <%= link_to "→ See costumes", costumes_path, class: "btn btn-gradient" %>
      </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-lewagon">
  <div class="nav-left">
    <span><%= link_to cl_image_tag("v1605715062/Costume_Carousel_black_jnj4lb.png", width: 150, height: 40), root_path %></span>
    <%= form_tag costumes_path, method: :get do %>
      <div class= "search">
        <%= text_field_tag :query, params[:query], class: "form-control"%>
        <%= button_tag type: 'submit', class: "btn btn-success postfix ml-1" do %>
          <i class="fas fa-search" aria-hidden="true"></i>
        <% end %>
      </div>
      <% end %>
    </div>
  <div>
    <%= link_to "See all costumes", costumes_path, class: "my-navbar-action" %> |
    <%= link_to "Dashboard", dashboard_index_path, class: "my-navbar-action"%>
    <% if user_signed_in? %>
      | <span class="my-navbar-action">User: <%= current_user&.email %></span>
    <% end %>
    <%= link_to "+ Add costume", new_costume_path, class: "btn btn-success ml-3" %>
  </div>
</div>